name: CI/CD
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request: {}
env:
  POETRY_VERSION: "1.8.2"
  OS_VERSION: "ubuntu-latest"
jobs:
  quality:
    name: Quality (python${{ matrix.python-version }})
    uses: ./.github/workflows/quality.yaml
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
    with:
      os: ${{ env.OS_VERSION }}
      python-version: ${{ matrix.python-version }}
      poetry-version: ${{ env.POETRY_VERSION }}
  test:
    name: Test (python${{ matrix.python-version }})
    uses: ./.github/workflows/test.yaml
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    with:
      os: ${{ env.OS_VERSION }}
      python-version: ${{ matrix.python-version }}
      poetry-version: ${{ env.POETRY_VERSION }}
